application:
  subdomain: rpub
  background_task: true
  multi_instance: true
  public_path:
    - /

  injects:
    - id: basic-auth
      on: request
      auth_required: false
      when:
        - "/*"
      do: |
        ctx.headers.set("Authorization", "Basic " + ctx.base64.encode("{{ .U.rpub_username }}:{{ .U.rpub_password }}"));

  upstreams:
    - location: /
      backend: http://rpub:3000/

services:
  rpub:
    # ghcr.io/harshit181/rsspub:0.101.3
    image: registry.lazycat.cloud/czyt/harshit181/rsspub:f2359107ada08cf9
    binds:
      - /lzcapp/var/data:/app/data
      - /lzcapp/var/epubs:/app/static/epubs
    environment:
      - RUST_LOG=info
      - RPUB_USERNAME={{.U.rpub_username}}
      - RPUB_PASSWORD={{.U.rpub_password}}
      - EPUBS_HOST_DIR=/app/static/epubs
