min_os_version: 1.3.8
name: Rpub
package: community.lazycat.app.rpub
version: 0.93.3
description: "一个自托管的 Rust 应用程序，它可以将你最喜欢的 RSS/Atom Rss转换成个人日报（EPUB）供你电子书阅读器或平板电脑阅读。"
homepage: https://github.com/harshit181/RPub
author: harshit181
application:
  subdomain: rpub
  background_task: true
  multi_instance: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://rpub:3000/

services:
  rpub:
    #  ghcr.io/harshit181/rpub:0.93.3
    image: registry.lazycat.cloud/czyt/harshit181/rpub:0e3b04ed4f5c5234
    container_name: rpub
    binds:
      - /lzcapp/var/data:/app/data
      - /lzcapp/var/epubs:/app/static/epubs
    environment:
      - RUST_LOG=info
      - RPUB_USERNAME={{.U.rpub_username}}
      - RPUB_PASSWORD={{.U.rpub_password}}

locales:
  zh:
    name: "Rpub"
    description: "一个自托管的 Rust 应用程序，它可以将你最喜欢的 RSS/Atom Rss转换成个人日报（EPUB）供你电子书阅读器或平板电脑阅读。"
  en:
    name: "Rpub"
    description: "A self-hosted Rust application that turns your favorite RSS/Atom feeds into a personal daily newspaper (EPUB)."
